name: tf_prior_activity
channels:
  - conda-forge
  - defaults
dependencies:
  - r-base>=4.2.0
  - r-essentials
  - r-data.table>=1.14.0
  - r-doparallel>=1.0.17
  - r-foreach>=1.5.2
  - r-optparse>=1.7.3
  - bioconductor-genomicranges
  - bioconductor-rtracklayer
  - bioconductor-genomeinfodb
  - bioconductor-biostrings
  - bioconductor-bsgenome.hsapiens.ucsc.hg38 